s="Tops Technologies"
print(s)
print(s.capitalize())
print(s.casefold())
print(s.upper())
print(s.lower())
print(s.center(40,"&"))
print(s.count("o"))
print(s.endswith("es"))
print(s.startswith("o"))
print(s.find("log"))
print(s.index("T",3))
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops".isalpha())
print("123".isnumeric())
print(" ".isspace())
print(s.title())
print("Tops".islower())
print("TOPS".isupper())
print("hello".replace("l","w"))
print(s.swapcase())
print("my name is jeet".title())
